### ISSUE TITLE
Example Map & Model Suggestions

### ISSUE THREAD

**Issue by DennisSmolek** [lucas-jones/three-lightmap-baker#2]
Hey man!

I'm really impressed with your work so far and I think there's a lot of people who would also be interested, especially with the utilization of three-mesh-bvh and the pathtracer..

There's been some great work on another lightmapper: https://github.com/pmndrs/react-three-lightmap
And the article on it: https://unframework.com/portfolio/simple-global-illumination-lightmap-baker-for-threejs/

It seems there's a good amount of crossover with things on both libraries wishlists so I think worth looking into...

### However... the main Demos**, _(which are super awesome)_ 

have some rights/src clearance issues that I think should get cleared up before it's shared or posted on showcases etc..

Something like [THIS](https://sketchfab.com/3d-models/level-blockout-24b39d9beef54166a14e6f2542d01def)  
![Screen Shot 2022-09-20 at 13 05 26](https://user-images.githubusercontent.com/1397052/191332056-3c1f4c66-2289-4a2b-b67c-b3014648b9b9.png)

Would probably be a good fit..

[This is a cool rocky/alien arena](https://sketchfab.com/3d-models/geonosis-arena-797d475ee192467399c0ee6ee15b41ed)

If this is just a personal thing then no worries!
but I think it would fit in really well with some other amazing things happening in the JS/React/3D space if you're open to it..

Let me know what you think, I'm up to help however I can too if you need it.

Again, Really great work!

**Comment by lucas-jones** [comment]
Thank you! I will replace the copyrighted maps as this project has gained some interest

**Comment by gkjohnson** [comment]
There are also some similarities to `@react-three-fiber/drei's` `<AccumulativeShadows>` component:

- https://drei.pmnd.rs/?path=/story/staging-accumulativeshadows--accumulative-shadow-st
- https://codesandbox.io/s/ancient-sea-4gy946?file=/src/App.js:2040-2059

All these libraries use a different approach (jittered light for soft shadows, light probes for the link in the OP) and should give a sense for how people are using these types of libraries already - but raytracing for light maps and AO baking should give the most robust solution at the cost of a bit of performance. Though should be possible to achieve a similar use experience.

**Comment by lucas-jones** [comment]
![image](https://user-images.githubusercontent.com/809463/191367772-41d5cabc-5ed1-4c23-968c-9a72f81d080a.png)

I've force pushed to remove the levels. I've added the one you linked :)

**Comment by gkjohnson** [comment]
Nice! One thing to note is the license of the linked models are "CC Attribution" which means you should at least credit the artist and maybe link to the sketchfab page somewhere in the README or example.

**Comment by DennisSmolek** [comment]
Awesome! and so fast too! 

I saw the credit in the readme so I'll go ahead and close this, 

Great Job!
